// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyC9StHxadvNsNbdUYI2Y9kb7zogk80Ly4o",
      authDomain: "my-firebase-project-b1913.firebaseapp.com",
      projectId: "my-firebase-project-b1913",
      storageBucket: "my-firebase-project-b1913.appspot.com",
      messagingSenderId: "65491281465",
      appId: "1:65491281465:web:f76da397475e4ea1d70fe8",
      measurementId: "G-1QWX6LZDDP"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyc28P7bkUBrcNU83g5oOYbtr1boT1kyY',
    appId: '1:65491281465:android:4b034b366cff1f29d70fe8',
    messagingSenderId: '65491281465',
    projectId: 'my-firebase-project-b1913',
    storageBucket: 'my-firebase-project-b1913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqAGt7cCshrPC9cSK4Fy5xQgLj4WPmuyM',
    appId: '1:65491281465:ios:8e9e664c3a68697dd70fe8',
    messagingSenderId: '65491281465',
    projectId: 'my-firebase-project-b1913',
    storageBucket: 'my-firebase-project-b1913.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqAGt7cCshrPC9cSK4Fy5xQgLj4WPmuyM',
    appId: '1:65491281465:ios:8e9e664c3a68697dd70fe8',
    messagingSenderId: '65491281465',
    projectId: 'my-firebase-project-b1913',
    storageBucket: 'my-firebase-project-b1913.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9StHxadvNsNbdUYI2Y9kb7zogk80Ly4o',
    appId: '1:65491281465:web:e18097fa4ce362ddd70fe8',
    messagingSenderId: '65491281465',
    projectId: 'my-firebase-project-b1913',
    authDomain: 'my-firebase-project-b1913.firebaseapp.com',
    storageBucket: 'my-firebase-project-b1913.appspot.com',
    measurementId: 'G-N4Y1N65FD5',
  );
}
